---
## Deployment K6
apiVersion: v1
kind: Pod
metadata:
  name: k6-machine-1
  namespace: test
  label:
    type: test
    app: k6-machine-1

spec:
#   initContainers: 
#     - name: init-script-downloader
#       image: appropriate/curl
#       args:
#         - "-o"
#         - "/home/scripts/test.js"
#         - "https://raw.githubusercontent.com/BuiDucAnh68/K8s_demo/main/test.js"
#       volumeMounts:
#       - name: filek6
#         mountPath: /home/scripts/
  containers:
    - name: k6-machine-1
      image: ducanh68/xk6-output-prometheus-remote:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      ports:
        - name: k6-port-1
          containerPort: 6565
      command: ["/bin/sh","-c","apk update --no-cache && apk add curl --no-cache && curl -o /home/scripts/test.js https://raw.githubusercontent.com/BuiDucAnh68/K8s_demo/main/test.js && K6_PROMETHEUS_RW_SERVER_URL=http://103.245.250.55/api/v1/write k6 run -o xk6-prometheus-rw -o json=/home/scripts/test.json /home/scripts/test.js && cat /home/scripts/test.json"]
      resources: {}
      volumeMounts:
        - name: filek6
          mountPath: /home/scripts/
        - name: varlog
          mountPath: /var/log/pods/

  volumes:
    - name: filek6
      emptyDir: {}
    - name: varlog
      emptyDir: {}

---
apiVersion: v1
kind: Pod
metadata:
  name: k6-machine-2
  namespace: test
  label:
    type: test
    app: k6-machine-2
spec:
  containers:
    - name: k6-machine-2
      image: ducanh68/xk6-output-prometheus-remote:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      ports:
        - name: k6-port-2
          containerPort: 6565
      command: ["/bin/sh","-c","apk update --no-cache && apk add curl --no-cache && curl -o /home/scripts/stresstest.js https://raw.githubusercontent.com/BuiDucAnh68/K8s_demo/main/stresstest.js && K6_PROMETHEUS_RW_SERVER_URL=http://103.245.250.55/api/v1/write k6 run -o xk6-prometheus-rw  /home/scripts/stresstest.js"]
      resources: {}
      volumeMounts:
        - name: filek6
          mountPath: /home/scripts/
        - name: varlog
          mountPath: /var/log/pods/

  volumes:
    - name: filek6
      mptyDir: {}
    - name: varlog
      emptyDir: {}
