# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: k6-pv
#   namespace: devops-tools
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 2Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: k6-pvc
#   namespace: devops-tools
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
---
## Deployment K6
apiVersion: v1
kind: Pod
metadata:
  name: k6-machine
  namespace: monitoring

spec:
  containers:
    - name: k6-machine
      image: ducanh68/xk6-output-prometheus-remote:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      ports:
        - name: k6-port
          containerPort: 6565
      command: ["/bin/sh"]
      args: ["-c","curl -o /home/scripts/ https://github.com/BuiDucAnh68/K8s_demo/blob/main/test.js;k6 run /home/scripts/test.js"]
      resources: {}
      volumeMounts:
        - name: filek6
          mountPath: /home/scripts/
        - name: varlog
          mountPath: /var/log/pods/

  volumes:
    - name: filek6
      hostPath:
        path: test.js
        type: FileOrCreate
    - name: varlog
      emptyDir: {}
