# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: k6-pv
#   namespace: devops-tools
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 2Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: k6-pvc
#   namespace: devops-tools
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
---
## Deployment K6
apiVersion: v1
kind: Pod
metadata:
  name: k6-test
  namespace: devops-tools

spec:
  containers:
    - name: k6-test
      image: grafana/k6
      imagePullPolicy: Never
      securityContext:
        privileged: true
      ports:
        - name: k6-port
          containerPort: 6565
      command:
        - sleep
        - "3600"
      resources: {}
      volumeMounts:
        - name: filek6
          mountPath: /home/k6/
        - name: varlog
          mountPath: /var/log/pods/

  volumes:
    - name: filek6
      hostPath:
        path: /scripts/test.js
        type: FileOrCreate
    - name: varlog
      emptyDir: {}
