apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # Update the replicas from 2 to 4
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.1
        ports:
        - containerPort: 8080
        
---
apiVersion: v1
# kind là loại Service
kind: Service
metadata:
  name: nginx-svc
  namespace: test
spec:
  ports:
    # port bên ngoài của pods mà các pods có thể giao tiếp được với nhau
    - port: 80
      # port target với 8080 của deployment
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    # dựa theo app : nginx-deployment ở labels trên kia sẽ map với service này
    app: nginx-deployment
  type: ClusterIP
  template:
    spec:
      containers:
        - image: nginx

