---
## Deployment K6
apiVersion: v1
kind: Pod
metadata:
  name: k6-machine
  namespace: monitoring

spec:
  containers:
    - name: k6-machine
      image: ducanh68/xk6-output-influx-prometheus:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      ports:
        - name: k6-port
          containerPort: 6565
      command:
        - sleep
        - "1d"
      tty: true
      resources: {}
      volumeMounts:
        - name: filek6
          mountPath: /home/scripts/
        - name: varlog
          mountPath: /var/log/pods/

  volumes:
    - name: filek6
      emptyDir: {}
    - name: varlog
      emptyDir: {}
   

