apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: k6-deployment
  labels:
    app: k6-deployment
  namespace: monitoring
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k6-deployment
    namespace: monitoring
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
