
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6-deployment
  labels:
    app: k6-deployment
  namespace: monitoring  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k6-deployment
  template:
    metadata:
      labels:
        app: k6-deployment
    spec:
      containers:
      - name: k6-deployment
        image: ducanh68/xk6-output:latest
        securityContext:
          privileged: true
        command: ["/bin/sh","-c","apk add --no-cache curl && touch /home/test.js && curl https://raw.githubusercontent.com/BuiDucAnh68/K8s_demo/main/test.js -o /home/test.js && K6_INFLUXDB_ORGANIZATION=gpc K6_INFLUXDB_TOKEN=3gORsO0Dmg53nfx-sQUy40YFZv1I6SubKq-Os-To_iMcjNo7skJV_UJZPidg7WCoqlo-ys4Ag4MNWMMi_lLgvA==  K6_INFLUXDB_BUCKET=gpc_store K6_PROMETHEUS_RW_SERVER_URL=http://10.0.128.65:9090/api/v1/write  k6 run -o xk6-influxdb=http://10.0.113.188:8086/ -o xk6-prometheus-rw /home/test.js", "sleep 1d"]
        resources:
          limits:
            memory: "1000Mi"
            cpu: "200m"
        ports:
        - containerPort: 6565

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: k6-horizontal
  labels:
    app: k6-horizontal
  namespace: monitoring
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k6-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10

