name: Pipeline CI/CD K6
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
        
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-actions@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD_TOKEN }}
          
      - name: deploy to cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        with:
          args: kubectl apply -f K8s/deployment.yaml
