name: Pipeline CI/CD K6
on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
jobs:
  build_deploy_k6: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Package
        run: |
          sudo apt-get update -y
          sudo apt-get install make wget curl git -y
      
      - name: Config Golang
        uses: actions/setup-go@v3
        with: 
          go-version:  '>=1.18.1'
      
      - name: Config Kubectl
        uses: ThomasKliszowski/setup-kubectl@v1
        with:
          kube-config: ${{ secrets.KUBE_CONFIG }}
          kube-version: 1.25.0

      - name: Run Kubectl test
        run: kubectl get namespace
      
      - name: Delete Pod Exists
        run: kubectl delete pod/k6-machine -n test
       
      
      - name: Deploy and Run pod K6
        run: kubectl apply -f https://raw.githubusercontent.com/BuiDucAnh68/K8s_demo/main/K6-Machine/Pod.yaml --validate=false 
      
      
        
#       - name: Deploy K6-Operator
#         uses: wahyd4/kubectl-helm-action@master
#         env:
#           KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
#         with:
#           args: kubectl apply -f https://raw.githubusercontent.com/BuiDucAnh68/K8s_demo/main/k8spod.yaml --validate=false
          
          
#       - name: Create/Modify deployment
#         uses: gane5hvarma/kubectl-actions@master
#         env:
#           KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
#         with:
#           args: apply -f ./K8s/deployment.yaml --validate=false
