name: pipeline K6
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Deploy Pod to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update image version
        id: ducanh68
        uses: mikefarah/yq@master
        with:
         cmd: yq eval '.spec.template.spec.containers[0].image = "${{ github.event.client_payload.image }}"' -i K8s/deployment.yaml
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
         commit_message: Apply image name changes
