name: Pipeline CI/CD K6
on:
  push:
    branches: [main]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - uses: ./.github/workflows/main.yml 
        run: |
          sudo apt-get update -y
          sudo apt-get install make wget curl tar git -y

      - name: Config Golang
        uses: actions-setup-got@v3
        with: 
          go-version:  '>=1.18.1'
      - name: Test config go
        run: go version

      - name: Create/Modify deployment
        uses: gane5hvarma/kubectl-actions@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./K8s/deployment.yaml --validate=false
