name: Pipeline CI/CD K6
on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Package
        run: |
          sudo apt-get update -y
          sudo apt-get install make wget curl git -y
      
      - name: Config Golang
        uses: actions/setup-go@v3
        with: 
          go-version:  '>=1.18.1'
     
      - name: Deploy K6-Operator
        uses: myrotvorets/kubectl-action@2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG }}
          version: latest
          args: kubectl get namespace
          
#         run: |
#           cd ./k6-operator
#           make deploy
          
#       - name: Create/Modify deployment
#         uses: gane5hvarma/kubectl-actions@master
#         env:
#           KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
#         with:
#           args: apply -f ./K8s/deployment.yaml --validate=false
