name: pipeline K6
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Deploy Pod to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync ArgoCD Application
        uses: omegion/argocd-actions@master
        with:
#           address: "vault.example.com"
          token: ${{ secrets.ARGOCD_TOKEN }}
          action: sync
          appName: "syncargocd"
