name: Pipeline CI/CD K6
on:
  push:
    branches: [main]
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu
    steps: 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-actions@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD_TOKEN }}
          
      - name: Push Chanege
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: K8s/deployment.yml
          destination_repo: BuiDucAnh68/K8s_demo
          destination_branch: main
          destination_folder: K8s
