name: pipeline K6
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  deploy:
    name: Deploy Pod to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Update version
        uses: apt-get update -y
      - name: Install Curl
        uses: apt install curl -y
      - name: Install Kubectl Step 1
        uses: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - name: Install kubectl Step 2
        uses: sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - name: Install Finish
        uses: sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl 
      - name: Create KubeConfig
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
          cat ${HOME}/.kube/config
      # - name: Deploy K6
      #   uses: kubectl apply -f https://raw.githubusercontent.com/BuiDucAnh68/K8s_demo/main/k8spod.yaml
